# Generated by Django 4.2.7 on 2026-01-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='user',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='resume_uploaded',
        ),
        migrations.RemoveField(
            model_name='user',
            name='skill_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_time_spent',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='learning_style',
            field=models.CharField(choices=[('Visual', 'Visual'), ('Auditory', 'Auditory'), ('Kinesthetic', 'Kinesthetic'), ('Reading/Writing', 'Reading/Writing')], default='Visual', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='target_role',
            field=models.CharField(default='Student', max_length=100),
        ),
    ]
