# Generated by Django 4.2.7 on 2026-01-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userproficiencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproficiencies',
            name='calibration_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userproficiencies',
            name='standard_error',
            field=models.FloatField(default=0.0),
        ),
    ]
