# Generated by Django 4.2.7 on 2026-01-16 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_theta', models.FloatField(default=0.0)),
                ('current_se', models.FloatField(default=1.0)),
                ('question_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('converged', 'Converged'), ('abandoned', 'Abandoned'), ('completed', 'Completed')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_sessions', to='skills.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'diagnostic_sessions',
                'indexes': [models.Index(fields=['user', 'skill', 'status'], name='diagnostic__user_id_ed64a2_idx'), models.Index(fields=['status', 'last_activity'], name='diagnostic__status_762129_idx')],
            },
        ),
    ]
