# Generated by Django 4.2.7 on 2026-01-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticsession',
            name='question_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
