# Generated by Django 4.2.7 on 2026-01-16 07:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticsession',
            name='question_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('correct_answer', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('difficulty_b', models.FloatField(help_text='IRT difficulty parameter')),
                ('discrimination_a', models.FloatField(default=1.0)),
                ('guessing_c', models.FloatField(default=0.25, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('times_used', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
                ('generated_by_ai', models.BooleanField(default=False)),
                ('generation_prompt', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='skills.skill')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('is_correct', models.BooleanField()),
                ('theta_before', models.FloatField()),
                ('theta_after', models.FloatField()),
                ('se_before', models.FloatField()),
                ('se_after', models.FloatField()),
                ('time_taken_seconds', models.IntegerField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_logs', to='assessment.questionbank')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessment.diagnosticsession')),
            ],
            options={
                'db_table': 'answer_logs',
                'indexes': [models.Index(fields=['session', 'answered_at'], name='answer_logs_session_722935_idx'), models.Index(fields=['question', 'is_correct'], name='answer_logs_questio_27bd29_idx')],
            },
        ),
    ]
