# Generated by Django 4.2.7 on 2026-01-21 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0002_alter_diagnosticsession_question_count_questionbank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.FloatField(help_text='Current theta')),
                ('required_level', models.FloatField(help_text='Required theta for occupation')),
                ('gap_score', models.FloatField(help_text='required - current')),
                ('criticality_coefficient', models.FloatField(default=1.0, help_text='Weight based on importance and prerequisites')),
                ('priority_score', models.FloatField(help_text='gap_score * criticality_coefficient')),
                ('addressed', models.BooleanField(default=False)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_gaps', to='skills.occupation')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_gaps', to='skills.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'skill_gaps',
                'ordering': ['-priority_score'],
                'indexes': [models.Index(fields=['user', 'priority_score'], name='skill_gaps_user_id_ccdd71_idx'), models.Index(fields=['addressed'], name='skill_gaps_address_a75a95_idx')],
                'unique_together': {('user', 'occupation', 'skill')},
            },
        ),
    ]
