# Generated by Django 4.2.7 on 2026-01-21 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_remove_cfuquiz_lesson_remove_remediation_cfu_attempt_and_more'),
        ('assessment', '0003_skillgap'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFUQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.JSONField()),
                ('passing_score', models.IntegerField(default=70)),
                ('generation_prompt', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_cfu_quizzes', to='learning.lesson')),
            ],
        ),
    ]
