# Generated by Django 4.2.7 on 2026-01-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_cfuquiz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CFUQuiz',
        ),
    ]
