# Generated by Django 4.2.7 on 2026-01-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_delete_cfuquiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillgap',
            name='criticality_coefficient',
            field=models.FloatField(default=1.0, help_text='Weight based on importance'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['skill', 'difficulty_b'], name='question_ba_skill_i_182436_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['difficulty_b'], name='question_ba_difficu_6de353_idx'),
        ),
        migrations.AlterModelTable(
            name='questionbank',
            table='question_bank',
        ),
    ]
