# Generated by Django 4.2.7 on 2026-01-24 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('evaluated', 'Evaluated')], default='active', max_length=20)),
                ('current_question_number', models.PositiveIntegerField(default=0)),
                ('target_question_count', models.PositiveIntegerField(default=10)),
                ('question_generator_model', models.CharField(default='gemini-1.5-flash', max_length=50)),
                ('evaluator_model', models.CharField(default='gemini-1.5-pro', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('occupation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skills.occupation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conversation_sessions',
            },
        ),
        migrations.CreateModel(
            name='InterviewEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_score', models.FloatField()),
                ('behavioral_score', models.FloatField()),
                ('structural_score', models.FloatField()),
                ('overall_score', models.FloatField()),
                ('technical_feedback', models.JSONField(default=dict)),
                ('behavioral_feedback', models.JSONField(default=dict)),
                ('structural_feedback', models.JSONField(default=dict)),
                ('overall_feedback', models.TextField()),
                ('improvement_areas', models.JSONField(default=list)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='interview.conversationsession')),
            ],
            options={
                'db_table': 'interview_evaluations',
            },
        ),
        migrations.CreateModel(
            name='InterviewTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.PositiveIntegerField()),
                ('speaker', models.CharField(choices=[('interviewer', 'Interviewer (AI)'), ('candidate', 'Candidate (User)')], max_length=20)),
                ('text_content', models.TextField()),
                ('audio_url', models.URLField(blank=True, max_length=500)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='interview.conversationsession')),
            ],
            options={
                'db_table': 'interview_turns',
                'ordering': ['turn_number'],
                'unique_together': {('session', 'turn_number')},
            },
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['user', 'status'], name='conversatio_user_id_59437c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['started_at'], name='conversatio_started_271f1b_idx'),
        ),
    ]
