# Generated by Django 4.2.7 on 2026-01-21 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFUAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(help_text='User answers')),
                ('score', models.IntegerField()),
                ('passed', models.BooleanField()),
                ('time_taken_seconds', models.IntegerField(blank=True, null=True)),
                ('remediation_generated', models.BooleanField(default=False)),
                ('attempt_number', models.IntegerField(default=1)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cfu_attempts',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.IntegerField(help_text='Order in study plan')),
                ('estimated_hours', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('primary_skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_modules', to='skills.skill')),
            ],
            options={
                'db_table': 'learning_modules',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Generation'), ('generating', 'Generating'), ('ready', 'Ready'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('skill_gaps_snapshot', models.JSONField(default=dict)),
                ('total_modules', models.IntegerField(default=0)),
                ('completed_modules', models.IntegerField(default=0)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('generated_by_model', models.CharField(default='gemini-1.5-pro', max_length=50)),
                ('generation_prompt', models.TextField(blank=True)),
                ('batch_job_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to='skills.occupation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'study_plans',
            },
        ),
        migrations.CreateModel(
            name='Remediation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('misconception', models.CharField(max_length=500)),
                ('explanation', models.TextField()),
                ('simplified_content', models.TextField()),
                ('additional_examples', models.JSONField(default=list)),
                ('helpful', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cfu_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediations', to='learning.cfuattempt')),
            ],
            options={
                'db_table': 'remediations',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='AI-generated lesson content')),
                ('learning_objectives', models.JSONField(default=list)),
                ('order', models.IntegerField()),
                ('estimated_minutes', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('available', 'Available'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='locked', max_length=20)),
                ('generated_by_model', models.CharField(default='gemini-2.0-flash-lite', max_length=50)),
                ('generation_prompt', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.learningmodule')),
            ],
            options={
                'db_table': 'lessons',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='study_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_modules', to='learning.studyplan'),
        ),
        migrations.CreateModel(
            name='CFUQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.JSONField(help_text='List of quiz questions with options')),
                ('passing_score', models.IntegerField(default=70)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generation_prompt', models.TextField(blank=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfu_quizzes', to='learning.lesson')),
            ],
            options={
                'verbose_name': 'CFU Quiz',
                'verbose_name_plural': 'CFU Quizzes',
                'db_table': 'cfu_quizzes',
            },
        ),
        migrations.AddField(
            model_name='cfuattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.cfuquiz'),
        ),
        migrations.AddField(
            model_name='cfuattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfu_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='studyplan',
            index=models.Index(fields=['user', 'status'], name='study_plans_user_id_2d6fba_idx'),
        ),
        migrations.AddIndex(
            model_name='studyplan',
            index=models.Index(fields=['status'], name='study_plans_status_ddde79_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'status'], name='lessons_module__080b57_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='learningmodule',
            unique_together={('study_plan', 'order')},
        ),
        migrations.AddIndex(
            model_name='cfuattempt',
            index=models.Index(fields=['user', 'quiz'], name='cfu_attempt_user_id_617b0d_idx'),
        ),
        migrations.AddIndex(
            model_name='cfuattempt',
            index=models.Index(fields=['passed'], name='cfu_attempt_passed_c0763d_idx'),
        ),
    ]
