# Generated by Django 4.2.7 on 2026-01-21 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cfuquiz',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='remediation',
            name='cfu_attempt',
        ),
        migrations.DeleteModel(
            name='CFUAttempt',
        ),
        migrations.DeleteModel(
            name='CFUQuiz',
        ),
        migrations.DeleteModel(
            name='Remediation',
        ),
    ]
