# Generated by Django 4.2.7 on 2026-01-21 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('learning', '0002_remove_cfuquiz_lesson_remove_remediation_cfu_attempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningmodule',
            name='order',
            field=models.PositiveIntegerField(help_text='Order in study plan'),
        ),
        migrations.AlterField(
            model_name='learningmodule',
            name='primary_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_modules', to='skills.skill'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='estimated_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='generated_by_model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='completed_modules',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='generated_by_model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='total_modules',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
