# Generated by Django 4.2.7 on 2026-01-21 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0001_initial'),
        ('learning', '0003_alter_learningmodule_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFUAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(help_text='User answers')),
                ('score', models.IntegerField()),
                ('passed', models.BooleanField()),
                ('time_taken_seconds', models.IntegerField(blank=True, null=True)),
                ('remediation_generated', models.BooleanField(default=False)),
                ('attempt_number', models.IntegerField(default=1)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cfu_attempts',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.AlterField(
            model_name='learningmodule',
            name='order',
            field=models.IntegerField(help_text='Order in study plan'),
        ),
        migrations.AlterField(
            model_name='learningmodule',
            name='primary_skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_modules', to='skills.skill'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='estimated_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='generated_by_model',
            field=models.CharField(default='gemini-2.0-flash-lite', max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='completed_modules',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='generated_by_model',
            field=models.CharField(default='gemini-1.5-pro', max_length=50),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='total_modules',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Remediation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('misconception', models.CharField(max_length=500)),
                ('explanation', models.TextField()),
                ('simplified_content', models.TextField()),
                ('additional_examples', models.JSONField(default=list)),
                ('helpful', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cfu_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediations', to='learning.cfuattempt')),
            ],
            options={
                'db_table': 'remediations',
            },
        ),
        migrations.CreateModel(
            name='CFUQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.JSONField(help_text='List of quiz questions with options')),
                ('passing_score', models.IntegerField(default=70)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generation_prompt', models.TextField(blank=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfu_quizzes', to='learning.lesson')),
            ],
            options={
                'verbose_name': 'CFU Quiz',
                'verbose_name_plural': 'CFU Quizzes',
                'db_table': 'cfu_quizzes',
            },
        ),
        migrations.AddField(
            model_name='cfuattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.cfuquiz'),
        ),
        migrations.AddField(
            model_name='cfuattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfu_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cfuattempt',
            index=models.Index(fields=['user', 'quiz'], name='cfu_attempt_user_id_617b0d_idx'),
        ),
        migrations.AddIndex(
            model_name='cfuattempt',
            index=models.Index(fields=['passed'], name='cfu_attempt_passed_c0763d_idx'),
        ),
    ]
