# Generated by Django 4.2.7 on 2026-01-12 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esco_uri', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('onet_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('preferred_label', models.CharField(max_length=255)),
                ('alternative_labels', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='skills.occupation')),
            ],
            options={
                'db_table': 'occupations',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esco_uri', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('preferred_label', models.CharField(max_length=255)),
                ('alternative_labels', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('skill_type', models.CharField(choices=[('technical', 'Technical'), ('soft', 'Soft'), ('knowledge', 'Knowledge')], max_length=20)),
                ('embeddings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='required_for', to='skills.skill')),
            ],
            options={
                'db_table': 'skills',
            },
        ),
        migrations.CreateModel(
            name='SkillEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField(default=list)),
                ('model_name', models.CharField(default='text-embedding-004', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='skills.skill')),
            ],
            options={
                'db_table': 'skill_embeddings',
            },
        ),
        migrations.CreateModel(
            name='OccupationSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.FloatField(default=0.5)),
                ('required_proficiency_theta', models.FloatField(default=0.0)),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.occupation')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skill')),
            ],
            options={
                'db_table': 'occupation_skills',
            },
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['preferred_label'], name='skills_preferr_71d7dc_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['skill_type'], name='skills_skill_t_50bcd8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='occupationskill',
            unique_together={('occupation', 'skill')},
        ),
        migrations.AddIndex(
            model_name='occupation',
            index=models.Index(fields=['preferred_label'], name='occupations_preferr_c04449_idx'),
        ),
        migrations.AddIndex(
            model_name='occupation',
            index=models.Index(fields=['onet_code'], name='occupations_onet_co_233c9d_idx'),
        ),
        migrations.AddIndex(
            model_name='occupation',
            index=models.Index(fields=['parent'], name='occupations_parent__e1ccc1_idx'),
        ),
    ]
